[project]
name = "MultiSeasonal_Matches"
version = "0.1.0"
description = "Tools for aligning and stitching multi-season camera images"
authors = [{ name="Kristen Such" }]
requires-python = ">=3.7"
dependencies = [
    "opencv-python",
    "shapely",
    "matplotlib",
    "geographiclib",
    "geopy",
    "psutil",
    "PyYAML",
    "scipy",
    "tqdm",
    "toml",
    "stitching",
    "py3rosmsgs"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]