[paths]
may_results = "/media/kristen/easystore2/RestorebotData/benchmarking_ex/May2022_1conmod/processed_results"
nov_results = "/media/kristen/easystore2/RestorebotData/benchmarking_ex/Nov2022_1conmod/1conmod/processed_results"
match_output_dir = "/media/kristen/easystore2/RestorebotData/benchmarking_ex/matches_fused"
may_images = "/media/kristen/easystore2/RestorebotData/benchmarking_ex/May2022_1conmod/Down_Facing_Images"
may_front_images = "/media/kristen/easystore2/RestorebotData/benchmarking_ex/May2022_1conmod/Front_Facing_Images"
nov_left_images = "/media/kristen/easystore2/RestorebotData/benchmarking_ex/Nov2022_1conmod/1conmod/Left_Down_Facing_Images"
nov_right_images = "/media/kristen/easystore2/RestorebotData/benchmarking_ex/Nov2022_1conmod/1conmod/Right_Down_Facing_Images"
nov_front_images = "/media/kristen/easystore2/RestorebotData/benchmarking_ex/Nov2022_1conmod/1conmod/Front_Facing_Images"
[stitching]
crop = false
confidence_threshold = 0.5